### ISSUE TITLE
bower ENOTFOUND     Package ion-dynamic-tree-list not found？

### ISSUE THREAD

**Issue by peny911** [ltung/ion-dynamic-tree-list#2]
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower not-cached    https://github.com/driftyco/ionic-bower.git#1.3.2
bower resolve       https://github.com/driftyco/ionic-bower.git#1.3.2
bower not-cached    https://github.com/fer/ion-tree-list.git#^0.0.11
bower resolve       https://github.com/fer/ion-tree-list.git#^0.0.11
bower download      https://github.com/driftyco/ionic-bower/archive/v1.3.2.tar.gz
bower download      https://github.com/fer/ion-tree-list/archive/v0.0.11.tar.gz
bower extract       ion-tree-list#^0.0.11 archive.tar.gz
bower resolved      https://github.com/fer/ion-tree-list.git#0.0.11
bower progress      ionic#1.3.2 received 0.6MB of 1.4MB downloaded, 39%
bower progress      ionic#1.3.2 received 0.6MB of 1.4MB downloaded, 42%
bower progress      ionic#1.3.2 received 0.7MB of 1.4MB downloaded, 45%
bower progress      ionic#1.3.2 received 0.7MB of 1.4MB downloaded, 48%
bower progress      ionic#1.3.2 received 0.7MB of 1.4MB downloaded, 51%
bower progress      ionic#1.3.2 received 0.8MB of 1.4MB downloaded, 53%
bower ENOTFOUND     Package ion-dynamic-tree-list not found

help me~~

**Comment by ltung** [comment]
Could you use github to download? I should probably close the bower download anyway since I myself upgrade it to Ionic 2 and couldn't figure out how to use bower to manage 2 versions of this dynamic tree?

**Comment by ltung** [comment]
I should change the README instructions accordingly also.

**Comment by peny911** [comment]
thanks very much
